name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build

  lint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Install Dependencies
        run: npm install
      - name: Lint Check
        run: npm run lint

  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Install Dependencies
        run: npm install
      - name: Format Check
        run: npm run format
